### ISSUE TITLE
bug: init: unit test error 

### ISSUE THREAD

**Issue by reemardelarosa** [qwikifiers/qwik-nx#15]
**Describe the bug**
After running test in qwik-nx, init.spec.ts is failing

**To Reproduce**

1. Run nx test qwik-nx
2. Wait for test to finish
3. See error in terminal
4. init.spec.ts is failing

**Expected behavior**
Unit test should all pass.

**Screenshots**
<img width="592" alt="Screenshot 2022-12-10 at 3 37 01 PM" src="https://user-images.githubusercontent.com/4918140/206838441-153f732f-d423-45af-87eb-2279bbdc010d.png">
<img width="783" alt="Screenshot 2022-12-10 at 3 37 53 PM" src="https://user-images.githubusercontent.com/4918140/206838480-0b293d8e-415f-41c2-afd9-fd4d228fcc98.png">

- OS: Apple M1 Pro
- Browser Chrome
- Version 107.0.5304.121 (Official Build) (arm64)
- Node 19.0.1

**Additional context**

**Comment by dmitry-stepanenko** [comment]
fixed by https://github.com/qwikifiers/qwik-nx/pull/43
