### ISSUE TITLE
nested folders do not play well with playwright e2e generator

### ISSUE THREAD

**Issue by dmitry-stepanenko** [qwikifiers/qwik-nx#153]
Project name will be incorrectly resolved if nested directory is provided. Most likely this is something to address in the playwright generator

**Comment by sebastiandg7** [comment]
I'll take a look at that. Will let you know once the fix is released.

**Comment by dmitry-stepanenko** [comment]
Thanks a lot!

**Comment by sebastiandg7** [comment]
@dmitry-stepanenko It took a little while! 😅 Fixing in nxkit/nxkit#88.

**Comment by sebastiandg7** [comment]
`@nxkit/playwright` v3.0.2 released containing the fix 🚀

**Comment by dmitry-stepanenko** [comment]
Awesome, thanks a lot @sebastiandg7 !

**Comment by dmitry-stepanenko** [comment]
resolved by https://github.com/qwikifiers/qwik-nx/pull/173
