### ISSUE TITLE
when installing qwik-nx, @nx* packages are being updated without running the migrations

### ISSUE THREAD

**Issue by NachoVazquez** [qwikifiers/qwik-nx#166]
### Current Behavior

When installing `qwik-nx`, @nx* dependencies get updated in the package.json without running the proper migrations.

For example, if I run

```bash
yarn add -D qwik-nx
```

And my dependencies are using `@nx*: 16.1.4`

They will get updated to `@nx*: 16.2.0` without running the necessary migrations.

### Expected Behavior

Running `yarn add -D qwik-nx` shouldn't hoist the other `@nx*: <version>` versions

### Steps to Reproduce

1. create a workspace using a lower version than the current one in qwik-nx
2.  run `yarn add -D qwik-nx`
3. see how it updates the package.json version of the other @nx* packages

### Nx Report

```shell
Node   : 18.12.1
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native

   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/angular        : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/webpack        : 16.1.4
   nx-cloud           : 16.0.5
   typescript         : 4.8.4
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 2.29.2
   ngx-deploy-npm    : 4.3.10
```

**Comment by dmitry-stepanenko** [comment]
Hey @NachoVazquez, thanks for raising this. I tried to reproduce it as follows:
- `npx create-nx-workspace@latest --preset=react --pm=yarn`
- `yarn add qwik-nx -D`

I used codespaces with "empty" container to run that.

It didn't bump any of the dependencies except installing the qwik-nx itself. Anything that I'm missing? qwik-nx itself is not bound to any specific version of nx, it has a dependency of `"@nx/devkit": "^16.0.0"` alongside few other Nx packages of the same version

**Comment by NachoVazquez** [comment]
That's interesting. I was streaming at the moment I saw this behavior, I can send you a clip of when it happened. 

Otherwise, I will attempt to reproduce it again. Thanks for the quick response.

**Comment by dmitry-stepanenko** [comment]
Yes please, if you provide steps to reproduce this, it will be awesome. It makes me think package manager failed to resolve version dependencies correctly for some reason and applied latest according to `^16.0.0` version despite having acceptable installed versions under node_modules.

**Comment by NachoVazquez** [comment]
I wasn't able to reproduce it in a clean repo, but thinking back, I think I ran yarn with some arguments like --install-deps or something like that because, after just doing. 

```bash
yarn add -D qwik-nx
```

I couldn't use the commands because I was missing @nx/vite and vite dependencies.

So not an issue at all, probably just me :)

**Comment by NachoVazquez** [comment]
Closing this :) Thanks for taking a look anyways!
