### ISSUE TITLE
feat: add tailwind configuration

### ISSUE THREAD

**Issue by dmitry-stepanenko** [qwikifiers/qwik-nx#20]
**Is your feature request related to a problem? Please describe.**
There's no ability to configure tailwind out of the box

**Describe the solution you'd like**
The flow is the same as in `@nrwl/react:setup-tailwind`, however it's undesirable to use that package

**Comment by reemardelarosa** [comment]
@dmitry-stepanenko @shairez can I work on this one or this is already in progress?

**Comment by shairez** [comment]
@reemardelarosa I think you can take this one
thanks! 🙏
