### ISSUE TITLE
feat: include react integration

### ISSUE THREAD

**Issue by dmitry-stepanenko** [qwikifiers/qwik-nx#36]
Should mimic this feature https://qwik.builder.io/integrations/integration/react/

**Comment by n8sabes** [comment]
Indeed, no way to run qwik scripts. Tried `pnpm qwik add react --filter qwik_project` from root workspace, and also `pnpm qwik add react` from the qwik project directory.

🤔 I suppose the workaround is to run against a non-Nx project and copy the changes.
