### ISSUE TITLE
Mitoses-nx would love to see mitoses with an NX plugin, this would complete my life.

### ISSUE THREAD

**Issue by algoflows** [qwikifiers/qwik-nx#37]
**Is your feature request related to a problem? Please describe.**
Yes being able to compile Qwik and other any other framework components from shared UI library.

**Describe the solution you'd like**
Mitoses as an NX plugin to handle component compilation.

**Describe alternatives you've considered**
None, we need this.

**Additional context**
We are counting on you :)

**Comment by sebastiandg7** [comment]
I don't think this is the right place for this issue. I started working on an experimental nx plugin for mitosis, I can ping you via twitter about any progess or I you'd like to do some testing.

**Comment by algoflows** [comment]
Absolutely, I've been waiting for this for so long! @_algoflows is my twitter, would be happy to test fasho!

**Comment by shairez** [comment]
thanks for the suggestion @algoflows 
agree with @sebastiandg7 
this should belong in another repo, so closing this for now
