### ISSUE TITLE
Qwik Contributor support needed for main branch, and local builds

### ISSUE THREAD

**Issue by n8sabes** [qwikifiers/qwik-nx#51]
**Describe the bug**
Qwik Contributor support needed for `main` branch, and local builds.

It took some fussing to find the root cause which is `qwik` / `Qwik-city` version sensitivities. **I've included a workaround below**.

@dmitry-stepanenko, thanks for the help diagnosing this!

**To Reproduce**

```
npx create-nx-workspace --preset=qwik-nx --e2eTestRunner=none
cd project
pnpm add -D https://github.com/builderio/qwik-build https://github.com/builderio/qwik-city-build
pnpm exec nx generate qwik-nx:application qwik --no-interactive --dry-run --verbose --e2eTestRunner=none
```

**Workaround**
Downgrade `qwik` and `Qwik-city`, run the `qwik-nx` generator, then re-upgrade to `main` branch or local `qwik` build.

**Comment by dmitry-stepanenko** [comment]
This is not an issue with qwik-nx, please track the progress in this PR to nrwl/nx, that I've created https://github.com/nrwl/nx/pull/14682
