### ISSUE TITLE
Publishing to verdaccio produces a TypeError

### ISSUE THREAD

**Issue by n8sabes** [qwikifiers/qwik-nx#55]
**Describe the bug**
Publishing to a local registry docs are not working and produce a TypeError.

**NOTE:** Once it's working, I am happy to add further clarification to the local pub doc.

**To Reproduce**
`nx publish qwik-nx --registry=http://localhost:4873` results in a `TypeError: Cannot read properties of undefined (reading 'defaultProject')`.

**Expected behavior**
Should publish to verdaccio.

**Additional context**
If there is another way to build and use `qwik-nx` locally without verdaccio, it would be nice to document that option for ease of using the main branch.

**Comment by dmitry-stepanenko** [comment]
Should no longer an issue after https://github.com/qwikifiers/qwik-nx/pull/84
