### ISSUE TITLE
feat: add "preset" generator 

### ISSUE THREAD

**Issue by dmitry-stepanenko** [qwikifiers/qwik-nx#7]
Create a "preset" generator for qwik, that can be used with `npx create-nx-workspace` https://nx.dev/packages/nx-plugin#custom-preset

**Comment by reemardelarosa** [comment]
@dmitry-stepanenko, I will start to work on this preset.

**Comment by reemardelarosa** [comment]
@dmitry-stepanenko , do you have pointers here that I need to consider?

**Comment by dmitry-stepanenko** [comment]
@reemardelarosa I think we should mimic the behavior they have, so this preset should have prompts for the app name and styles to use (like when you run `npx create-nx-workspace` => `integrated` => `angular` . Probably you will need my changes for the app generator, which are about to be merged

**Comment by shairez** [comment]
@all-contributors please add @reemardelarosa for code, tests, bug, doc, ideas, maintenance and review
