### ISSUE TITLE
feat: add e2e setup to application generator

### ISSUE THREAD

**Issue by dmitry-stepanenko** [qwikifiers/qwik-nx#9]
This functionality can be added once `@nrwl/vite` package finishes their implementation

**Comment by shairez** [comment]
Research this - 

https://github.com/marksandspencer/nx-plugins/tree/main/packages/nx-playwright

**Comment by sebastiandg7** [comment]
From [@nxkit/playwright](https://github.com/nxkit/nxkit/tree/main/packages/playwright) we expose the project generator. Using it would be as simple as:

```ts
import { projectGenerator } from '@nxkit/playwright';

await projectGenerator(tree, {
   name: 'qwik-app-e2e', // optional
   project: 'qwik-app'
});
```
