### ISSUE TITLE
no tsconfig.base.json is being added

### ISSUE THREAD

**Issue by shairez** [qwikifiers/qwik-nx#90]
**Describe the bug**
when qwik-nx is added to a nx workspace and generating a qwik app - no `tsconfig.base.json` is being added

**To Reproduce**

1. run `pnpx create-nx-workspace`
2. Choose the "packages project" option
3. run `pnpx add -D qwik-nx`
4. run `nx generate qwik-nx:application qwik-demo-app`

see that there's no `tsconfig.base.json`

**Expected behavior**
to generate a `tsconfig.base.json`

**Comment by dmitry-stepanenko** [comment]
@shairez this seems to be an issue on nx side https://github.com/nrwl/nx/issues/13977

Do you think it's worth adding it ourselves?
