### ISSUE TITLE
feat: add storybook configuration

### ISSUE THREAD

**Issue by dmitry-stepanenko** [qwikifiers/qwik-nx#93]
**Is your feature request related to a problem? Please describe.**
There's no ability to setup storybook configuration out of the box

**Describe the solution you'd like**
Should provide a generator `configure-storybook`, that will follow the same logic as Nx's storybook generators for Angular or React

**Comment by shairez** [comment]
@intellix seems like it was part of 0.14.1
https://github.com/qwikifiers/qwik-nx/releases/tag/qwik-nx-0.14.1

updating to latest should include it
