### ISSUE TITLE
Fails to create new workspace

### ISSUE THREAD

**Issue by vanvuongngo** [qwikifiers/qwik-nx#98]
**Describe the bug**
I am following the README to create a workspace. It worked in the past but not anymore.
I tried it on ubuntu and macos.

**To Reproduce**

nodejs 18.14.2
npm 9.6.0

calll create-nx-workspace
```
mkdir app && cd app
npm install -D qwik-nx
npx create-nx-workspace my-workspace --preset=qwik-nx
```

- Give a app name: myapp
- Choose stylesheet: css or sass
- script ends with `(0 , typescript_1.getRelativePathToRootTsConfig) is not a function`

**Expected behavior**
- create a new workspace w/o error

**Screenshots**

```
Installing dependencies with npm
✔ Nx has successfully created the workspace: vvng.

>  NX  Generating qwik-nx:preset

✔ App Name · nmail
✔ Which stylesheet format would you like to use? · css

 >  NX   (0 , typescript_1.getRelativePathToRootTsConfig) is not a function

   Pass --verbose to see the stacktrace.


 >  NX   Failed to apply preset: qwik-nx

   See above
```

**Desktop (please complete the following information):**

- OS: ubuntu and macos 12

**Additional context**

**Comment by dmitry-stepanenko** [comment]
There's a compatibility issue with nx 15.8, we'll have a new release hopefully today. 

You can temporarily stick to nx 15.7 by using `npx create-nx-workspace@15.7 my-workspace --preset=qwik-nx`

Thanks for raising this!

**Comment by vanvuongngo** [comment]
Thanks a lot for your quick workaround and awesome work.
